---
title: "First lesson."
author: "John Park"
date: "July 11, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rcrossref)
library(jsonlite)
```

## Get metadata from journal 

This is the first tutorial about using crossref API for getting text data from literatures. CrossRef API <https://github.com/CrossRef/rest-api-doc>.


```{r}
## example of work retrieving from jouranl 'landscape ecology'
issn.target='15729761-09212973'
DownPubs=cr_works(filter=c(issn=issn.target))

```
using crossref api: the command is,
https://api.crossref.org/works?facet=license:*&filter=issn:15729761-09212973

result is the same for crossref api and rcrossref. 

Since cr_works only takes first 20 dat points, set offset and do recurrent download based on the total number of publications found in the journal.  
```{r}
n_pages <- ceiling(DownPubs$meta$total_results / DownPubs$meta$items_per_page)

ls.pubs<-list()
for (i in 1:n_pages){
   n_line <- (i - 1)*20 + 1
  ls.pubs[[i]] <- cr_works(filter = c(issn=issn.target), offset = n_line)$data 
}
ls.pubs<-do.call("rbind",ls.pubs)
ls.pubs
```



